server:
    port: 1231
spring:
    datasource:
        driver-class-name: org.h2.Driver
        #url: jdbc:h2:file:d:/testdb
        url: jdbc:h2:mem:testdb
        username: test
        password: test
    h2:
      console:
          enabled: true
          path: /h2-test